/* ============================================================================
 * export-report.js — Automated Government Impact Reports (B2B SaaS feature)
 * ----------------------------------------------------------------------------
 * Plugs directly into the Admin Panel. It aggregates the verified clean-ups in
 * the admin's scope (their city, or all of Morocco if super admin), then uses
 * jsPDF to generate a formal, multi-page PDF document.
 * 
 * Flow:
 * 1. Injects a "Generate Impact PDF" button into the Admin context banner.
 * 2. On click, it dynamically loads jsPDF via CDN (zero initial cost).
 * 3. It calculates impact metrics (estimated kg removed, volunteers engaged,
 *    category breakdown).
 * 4. It renders a clean, professional PDF with a title page, data summary,
 *    and an appendix of the 6 most recent verified Before/After photos.
 * 5. Triggers a direct download to the admin's device.
 * ==========================================================================*/
(function () {
  'use strict';

  const L10N = {
    en: { btn: '📄 Export PDF Report', wait: 'Generating PDF...', err: 'Failed to generate PDF.', t_title: 'Environmental Impact Report', t_sub: 'Generated by EcoClean Connect', s_kpi: 'Key Performance Indicators', s_cat: 'Breakdown by Category', s_photo: 'Recent Verified Clean-ups', v_rep: 'Total Reports', v_ver: 'Verified Clean-ups', v_kg: 'Est. Waste Removed (kg)', v_vol: 'Active Volunteers', cat_id: 'Illegal Dumping', cat_pm: 'Plastic / Marine', cat_w: 'Water Pollution', cat_as: 'Air / Smoke', cat_o: 'Other', b: 'Before', a: 'After' },
    fr: { btn: '📄 Exporter le Rapport PDF', wait: 'Génération du PDF...', err: 'Échec de la génération du PDF.', t_title: 'Rapport d\'Impact Environnemental', t_sub: 'Généré par EcoClean Connect', s_kpi: 'Indicateurs Clés de Performance', s_cat: 'Répartition par Catégorie', s_photo: 'Nettoyages Vérifiés Récents', v_rep: 'Signalements Totaux', v_ver: 'Nettoyages Vérifiés', v_kg: 'Déchets Retirés (est. kg)', v_vol: 'Bénévoles Actifs', cat_id: 'Décharges sauvages', cat_pm: 'Plastique / Marin', cat_w: 'Pollution de l\'eau', cat_as: 'Air / Fumée', cat_o: 'Autre', b: 'Avant', a: 'Après' },
    ar: { btn: '📄 تصدير تقرير PDF', wait: 'جاري إنشاء PDF...', err: 'فشل إنشاء PDF.', t_title: 'تقرير الأثر البيئي', t_sub: 'تم إنشاؤه بواسطة EcoClean Connect', s_kpi: 'مؤشرات الأداء الرئيسية', s_cat: 'التوزيع حسب الفئة', s_photo: 'عمليات التنظيف المؤكدة الأخيرة', v_rep: 'إجمالي البلاغات', v_ver: 'عمليات التنظيف المؤكدة', v_kg: 'النفايات المُزالة (كغ تقديراً)', v_vol: 'المتطوعون النشطون', cat_id: 'رمي نفايات عشوائي', cat_pm: 'بلاستيك / بحري', cat_w: 'تلوث المياه', cat_as: 'هواء / دخان', cat_o: 'أخرى', b: 'قبل', a: 'بعد' }
  };
  const lang = () => (typeof window.getLang === 'function' ? getLang() : 'en');
  const t = (k) => (L10N[lang()] || L10N.en)[k];

  // Impact constants matching stats.js
  const KG_EST = { illegal_dumping: 35, plastic_marine: 18, water: 10, air_smoke: 0, other: 12 };

  function loadJsPDF() {
    return new Promise((resolve, reject) => {
      if (window.jspdf) return resolve(window.jspdf);
      const s = document.createElement('script');
      s.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js';
      s.onload = () => resolve(window.jspdf);
      s.onerror = reject;
      document.head.appendChild(s);
    });
  }

  // Preload an image to base64 so jsPDF can embed it
  function imgToBase64(url) {
    return new Promise((resolve) => {
      if (!url) return resolve(null);
      const img = new Image();
      img.crossOrigin = 'anonymous';
      img.onload = () => {
        const cvs = document.createElement('canvas');
        cvs.width = img.width; cvs.height = img.height;
        cvs.getContext('2d').drawImage(img, 0, 0);
        resolve({ data: cvs.toDataURL('image/jpeg', 0.8), w: img.width, h: img.height });
      };
      img.onerror = () => {
        const i2 = new Image();
        i2.onload = () => {
          const cvs = document.createElement('canvas');
          cvs.width = i2.width; cvs.height = i2.height;
          cvs.getContext('2d').drawImage(i2, 0, 0);
          resolve({ data: cvs.toDataURL('image/jpeg', 0.8), w: i2.width, h: i2.height });
        };
        i2.onerror = () => resolve(null);
        i2.src = url;
      };
      img.src = url;
    });
  }

  async function generatePDF() {
    // 1. Fetch current scope data
    const u = window.EcoAuth && window.EcoAuth.getUser ? window.EcoAuth.getUser() : null;
    const adminCtx = u && u.admin ? u.admin : (sessionStorage.getItem('ecoclean_admin') ? { scope: 'all' } : null);
    
    const res = await fetch('/api/reports', {
      headers: (window.EcoAuth && window.EcoAuth.getToken && window.EcoAuth.getToken()) 
        ? { 'Authorization': 'Bearer ' + window.EcoAuth.getToken() } 
        : (sessionStorage.getItem('ecoclean_admin') ? { 'x-admin-key': sessionStorage.getItem('ecoclean_admin') } : {})
    });
    if (!res.ok) throw new Error('Data fetch failed');
    const reports = await res.json();
    
    const verified = reports.filter(r => r.status === 'verified');
    let kg = 0;
    const cats = { illegal_dumping: 0, plastic_marine: 0, water: 0, air_smoke: 0, other: 0 };
    const vols = new Set();
    
    verified.forEach(r => {
      kg += KG_EST[r.category] || 0;
      cats[r.category] = (cats[r.category] || 0) + 1;
      if (r.reporterName && r.reporterName.toLowerCase() !== 'anonymous') vols.add(r.reporterName);
    });

    // 2. Initialize jsPDF
    const { jsPDF } = await loadJsPDF();
    const doc = new jsPDF({ orientation: 'p', unit: 'mm', format: 'a4' });
    const isRtl = lang() === 'ar';
    const margin = 20;
    const W = 210, H = 297;
    let y = 20;

    // Helper: text drawing with RTL support (rudimentary for jsPDF standard fonts)
    function write(text, size, x, yPos, font = 'helvetica', style = 'normal', color = [20, 36, 29]) {
      doc.setFont(font, style);
      doc.setFontSize(size);
      doc.setTextColor(color[0], color[1], color[2]);
      if (isRtl) {
        doc.text(text, W - x, yPos, { align: 'right' });
      } else {
        doc.text(text, x, yPos);
      }
    }

    // --- PAGE 1: Data Summary ---
    // Title
    doc.setFillColor(25, 135, 84); // EcoClean Green
    doc.rect(0, 0, W, 40, 'F');
    write(t('t_title'), 24, margin, 22, 'helvetica', 'bold', [255,255,255]);
    
    let scopeText = "Morocco (National)";
    if (adminCtx && adminCtx.scope === 'city') {
      scopeText = `${adminCtx.association_name} — ${adminCtx.city}`;
    }
    write(t('t_sub') + ' | ' + scopeText + ' | ' + new Date().toLocaleDateString(), 10, margin, 32, 'helvetica', 'normal', [230,243,239]);
    
    y = 60;
    write(t('s_kpi'), 16, margin, y, 'helvetica', 'bold');
    y += 15;
    
    // KPI Grid
    doc.setDrawColor(207, 226, 216);
    doc.setFillColor(245, 250, 247);
    const kpiBox = (label, val, xOffset) => {
      let bx = isRtl ? W - margin - xOffset - 80 : margin + xOffset;
      doc.roundedRect(bx, y, 80, 25, 3, 3, 'FD');
      write(String(val), 22, isRtl ? margin + xOffset + 40 : margin + xOffset + 40, y + 14, 'helvetica', 'bold', [10, 92, 63], true);
      write(label, 9, isRtl ? margin + xOffset + 40 : margin + xOffset + 40, y + 21, 'helvetica', 'normal', [93, 114, 104], true);
      if(isRtl) doc.text(String(val), W - bx - 40, y + 14, {align: 'center'});
      else doc.text(String(val), bx + 40, y + 14, {align: 'center'});
      if(isRtl) doc.text(label, W - bx - 40, y + 21, {align: 'center'});
      else doc.text(label, bx + 40, y + 21, {align: 'center'});
    };
    
    kpiBox(t('v_rep'), reports.length, 0);
    kpiBox(t('v_ver'), verified.length, 90);
    y += 35;
    kpiBox(t('v_kg'), kg, 0);
    kpiBox(t('v_vol'), vols.size, 90);
    y += 45;

    // Categories
    write(t('s_cat'), 16, margin, y, 'helvetica', 'bold');
    y += 15;
    const mapKey = { 'illegal_dumping':'cat_id', 'plastic_marine':'cat_pm', 'water':'cat_w', 'air_smoke':'cat_as', 'other':'cat_o' };
    Object.keys(cats).forEach(k => {
      const lbl = t(mapKey[k]) || k;
      const count = cats[k];
      write(lbl + ': ' + count, 12, margin, y);
      y += 8;
    });

    // --- PAGE 2: Photo Appendix ---
    const photos = verified.filter(r => r.beforePhoto && r.afterPhoto).slice(0, 4); // Top 4
    if (photos.length > 0) {
      doc.addPage();
      doc.setFillColor(25, 135, 84); doc.rect(0, 0, W, 25, 'F');
      write(t('s_photo'), 16, margin, 16, 'helvetica', 'bold', [255,255,255]);
      y = 40;

      for (let i = 0; i < photos.length; i++) {
        if (y > 240) { doc.addPage(); y = 20; }
        const p = photos[i];
        const dateStr = new Date(p.verifiedAt).toLocaleDateString();
        
        write((t(mapKey[p.category])||p.category) + ' — ' + dateStr, 12, margin, y, 'helvetica', 'bold');
        y += 6;
        
        const [b64B, b64A] = await Promise.all([imgToBase64(p.beforePhoto), imgToBase64(p.afterPhoto)]);
        const imgW = 80, imgH = 60;
        
        let lx = isRtl ? W - margin - imgW : margin;
        let rx = isRtl ? W - margin - 90 - imgW : margin + 90;

        if (b64B) doc.addImage(b64B.data, 'JPEG', lx, y, imgW, imgH);
        if (b64A) doc.addImage(b64A.data, 'JPEG', rx, y, imgW, imgH);
        
        doc.setFontSize(9); doc.setTextColor(93, 114, 104);
        if(isRtl) {
          doc.text(t('b'), W - lx - (imgW/2), y + imgH + 5, {align:'center'});
          doc.text(t('a') + ' ✅', W - rx - (imgW/2), y + imgH + 5, {align:'center'});
        } else {
          doc.text(t('b'), lx + (imgW/2), y + imgH + 5, {align:'center'});
          doc.text(t('a') + ' ✅', rx + (imgW/2), y + imgH + 5, {align:'center'});
        }
        
        y += imgH + 15;
      }
    }

    doc.save('EcoClean_Impact_Report.pdf');
  }

  // --- Injection ---
  function inject() {
    const ctxBox = document.getElementById('ecoAdminCtx');
    if (!ctxBox || document.getElementById('eco-pdf-btn')) return;

    const btn = document.createElement('button');
    btn.id = 'eco-pdf-btn';
    btn.className = 'primary-btn';
    btn.style.cssText = 'margin-top: 10px; width: auto; display: inline-flex; align-items: center; gap: 6px; padding: 8px 14px; font-size: .85rem;';
    btn.textContent = t('btn');
    
    btn.onclick = async () => {
      const old = btn.textContent;
      btn.textContent = t('wait');
      btn.disabled = true;
      try {
        await generatePDF();
      } catch (e) {
        console.error(e);
        alert(t('err'));
      }
      btn.textContent = old;
      btn.disabled = false;
    };

    ctxBox.appendChild(btn);
  }

  // Check periodically for the admin context box to render
  const intv = setInterval(() => {
    if (document.getElementById('ecoAdminCtx')) {
      inject();
      clearInterval(intv);
    }
  }, 500);

})();
